from exceptions.base_exception import BaseCustomHttpException


class UserExistsWithThisEmail(BaseCustomHttpException):
    pass
